{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jaxb-annotations",
    "version": "2.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.2.jar",
          "url": "jackson-module-jaxb-annotations-2.17.2.jar",
          "size": 36124,
          "sha512": "7700827471b95d93ac660b51370725a5b0e1e5bf11c051813468f0ff1d0fc6445ffd41209e88a2fb400be4266d52f282efd4e0f82a84701f8b4e954648bfb9b2",
          "sha256": "8e6c1d88db5a30a1431329521c7294d396579ca13e05181b40890007163cfbeb",
          "sha1": "f11051b7db74964c3611b52a701796411bd1a6fa",
          "md5": "3855a6f63408b2a4d84c8df2151b7729"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.2.jar",
          "url": "jackson-module-jaxb-annotations-2.17.2.jar",
          "size": 36124,
          "sha512": "7700827471b95d93ac660b51370725a5b0e1e5bf11c051813468f0ff1d0fc6445ffd41209e88a2fb400be4266d52f282efd4e0f82a84701f8b4e954648bfb9b2",
          "sha256": "8e6c1d88db5a30a1431329521c7294d396579ca13e05181b40890007163cfbeb",
          "sha1": "f11051b7db74964c3611b52a701796411bd1a6fa",
          "md5": "3855a6f63408b2a4d84c8df2151b7729"
        }
      ]
    }
  ]
}
