{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hivemq",
    "module": "hivemq-mqtt-client",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ppfzs5tbvffyfhj3weejwss3cu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.99.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec",
          "version": {
            "requires": "4.1.99.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.99.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.99.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.99.Final"
          }
        },
        {
          "group": "org.jctools",
          "module": "jctools-core",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.27"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ]
    },
    {
      "name": "websocketApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-websocket",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "websocketRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.99.Final"
          }
        }
      ],
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-websocket",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "proxyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-proxy",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "proxyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-handler-proxy",
          "version": {
            "requires": "4.1.99.Final"
          }
        }
      ],
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-proxy",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "epollApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-epoll",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "epollRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.99.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-transport-native-epoll",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3.jar",
          "url": "hivemq-mqtt-client-1.3.3.jar",
          "size": 1183511,
          "sha512": "dc71306288b34e0c1fb57057e52dd8c59fb0b73b35e43d26fbdf4fc003204c3be48ea10b99538161cde6ff6cd718d2e131c92d380c0762b5b761aacd2938cb58",
          "sha256": "3e0ae0103fbc39b22453cfd7b52152c0277741a30cf9fdee16bffc5fb70f8575",
          "sha1": "bdd803b91a30ac4b1df515cbb26c51ded16588b9",
          "md5": "be257f75d86efe2f40045e64d075cf34"
        }
      ],
      "capabilities": [
        {
          "group": "com.hivemq",
          "name": "hivemq-mqtt-client-epoll",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3-javadoc.jar",
          "url": "hivemq-mqtt-client-1.3.3-javadoc.jar",
          "size": 1343284,
          "sha512": "db8be96c1a16979b568cc2790087e2ba529a6bfc9002c11718524f9a9b9d2587d1e2cc72c46fcf1e9b199e9d7ca9d896eca62e17d2e0f06637dde40a136bd4f8",
          "sha256": "1ca45d25764d1b46f368450d6329176b855b1ca3b25f80e00bd7a73a28549654",
          "sha1": "07910734469a5a71cad40868684ed05207f62ac4",
          "md5": "97ea9a2f887b11be39d92ee5f6b56802"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hivemq-mqtt-client-1.3.3-sources.jar",
          "url": "hivemq-mqtt-client-1.3.3-sources.jar",
          "size": 709805,
          "sha512": "e302a47d38e2889a8c4f353bce92c91a584d54f8d7fd3e3315bd0e24b806d1f4d15428ee2cf2fc764fe923ea46b977d01cd438b4250dd8a45867fd1a4e92063b",
          "sha256": "a4a882444ce574380d0d44755c0481db414e71b86470bc23264672dce4410e2e",
          "sha1": "3a7675121a28ef67760a6488f13a2f28ed538067",
          "md5": "7212aae03b9abe44a7b9bae0d2839196"
        }
      ]
    }
  ]
}
