{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jakarta-xmlbind-annotations",
    "version": "2.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jakarta-xmlbind-annotations-2.17.2.jar",
          "url": "jackson-module-jakarta-xmlbind-annotations-2.17.2.jar",
          "size": 31441,
          "sha512": "b214f4d0be40b3cae01c681b07e5aa2e28c9e2c13cc08969b1e9a7c34e36524a70dda480c55ace4344d31bc9d6bc883d54ab9b60247f5989c077a92ff3e402d7",
          "sha256": "dd4937a4cec868a381ea413c285f8855be90bc5f7e6f3fa3291b8bb67f5ee22b",
          "sha1": "786788f3dd2641ea3961e009cd6875f486b49696",
          "md5": "661628bac9a89ac5ca46c64ca1826fd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jakarta-xmlbind-annotations-2.17.2.jar",
          "url": "jackson-module-jakarta-xmlbind-annotations-2.17.2.jar",
          "size": 31441,
          "sha512": "b214f4d0be40b3cae01c681b07e5aa2e28c9e2c13cc08969b1e9a7c34e36524a70dda480c55ace4344d31bc9d6bc883d54ab9b60247f5989c077a92ff3e402d7",
          "sha256": "dd4937a4cec868a381ea413c285f8855be90bc5f7e6f3fa3291b8bb67f5ee22b",
          "sha1": "786788f3dd2641ea3961e009cd6875f486b49696",
          "md5": "661628bac9a89ac5ca46c64ca1826fd1"
        }
      ]
    }
  ]
}
