{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jakarta-xmlbind-annotations",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jakarta-xmlbind-annotations-2.17.1.jar",
          "url": "jackson-module-jakarta-xmlbind-annotations-2.17.1.jar",
          "size": 31442,
          "sha512": "85a82c84ad632f26747d9a711d4502efb4caac9d949ccc290f0a1f3e7b570f5b3d09ba0511930beadb165a91df3825ee70618f9e39f3c75ca8c29a938304a8a3",
          "sha256": "c1f7976f52ef9b45ceb29cba976bb5f272519f193c32d77ac734ce80125d40cd",
          "sha1": "34252c6490d2a5d4352a3ce3e0bfe49cdbded75",
          "md5": "eeb3ffa405b2154190bab636532c529"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jakarta-xmlbind-annotations-2.17.1.jar",
          "url": "jackson-module-jakarta-xmlbind-annotations-2.17.1.jar",
          "size": 31442,
          "sha512": "85a82c84ad632f26747d9a711d4502efb4caac9d949ccc290f0a1f3e7b570f5b3d09ba0511930beadb165a91df3825ee70618f9e39f3c75ca8c29a938304a8a3",
          "sha256": "c1f7976f52ef9b45ceb29cba976bb5f272519f193c32d77ac734ce80125d40cd",
          "sha1": "34252c6490d2a5d4352a3ce3e0bfe49cdbded75",
          "md5": "eeb3ffa405b2154190bab636532c529"
        }
      ]
    }
  ]
}
