{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jakarta-jsonp",
    "version": "2.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jakarta-jsonp-2.17.2.jar",
          "url": "jackson-datatype-jakarta-jsonp-2.17.2.jar",
          "size": 21074,
          "sha512": "737ba2815c03d2274184afdd52685b304a70841e124f701a91fb4b40d07f4eff5a5a8200b3073a6d756d9a07f60ae309a3b4bfd29b220b7c8bf5ec1ff80c9a0a",
          "sha256": "a8673f03b1e096d51baa75059015ae080ab67f252aaa0e742e8159c841adfe5",
          "sha1": "d0cab87c53ff1b5320d5950a9008b73cccb97b2a",
          "md5": "af641b30289493cb9e62f408b336a7b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jakarta-jsonp-2.17.2.jar",
          "url": "jackson-datatype-jakarta-jsonp-2.17.2.jar",
          "size": 21074,
          "sha512": "737ba2815c03d2274184afdd52685b304a70841e124f701a91fb4b40d07f4eff5a5a8200b3073a6d756d9a07f60ae309a3b4bfd29b220b7c8bf5ec1ff80c9a0a",
          "sha256": "a8673f03b1e096d51baa75059015ae080ab67f252aaa0e742e8159c841adfe5",
          "sha1": "d0cab87c53ff1b5320d5950a9008b73cccb97b2a",
          "md5": "af641b30289493cb9e62f408b336a7b7"
        }
      ]
    }
  ]
}
